import type { Metadata } from "next";
import { ReactNode } from "react";
import Nav from "./_component/nav";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        {modal}
      </body>
    </html>
  );
}
